### PR TITLE
added an import of sys

### PR DESCRIPTION
**Pull request by tonetheman**
I will bite. I added a single import. So still wide open. Interesting idea.

### CODE REVIEW

**Review by Alexandre2006 — COMMENTED** [review]
You completely understand the goal of this project! Thanks for leaving an open canvas for everyone else.

**Comment by Alexandre2006** [comment]
> You completely understand the goal of this project! Thanks for leaving an open canvas for everyone else.

Please don't delete your branch though.

**Comment by tonetheman** [comment]
It failed your code checking standards step, figured you would not want it.  :(

**Comment by Alexandre2006** [comment]
It's fine. Anything is good to be completely honest.

**Pull request closed without merging**
